# Generated by Django 5.1.1 on 2024-09-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='coins_reward',
            field=models.IntegerField(help_text='Количество монет за получение достижения', null=True, verbose_name='Награда за выполнение (монеты)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.ForeignKey(blank=True, default=1, help_text='Звание пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.rank', verbose_name='Звание'),
        ),
    ]
