# Generated by Django 5.1.1 on 2024-09-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='photo_path',
        ),
        migrations.RemoveField(
            model_name='team',
            name='photo_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='achievement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
