# Generated by Django 5.1.1 on 2024-09-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_remove_achievement_photo_path_remove_team_photo_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
