# Generated by Django 5.1.1 on 2024-10-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, help_text='Статус выполнения задачи', on_delete=django.db.models.deletion.CASCADE, to='gamification.status', verbose_name='Статус'),
        ),
    ]
