# Generated by Django 5.1.1 on 2024-09-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_team_xp_alter_achievement_coins_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='coins_reward',
            field=models.PositiveIntegerField(help_text='Количество монет за выполнение задачи', null=True, verbose_name='Награда за выполнение (монеты)'),
        ),
    ]
