# Generated by Django 5.1.1 on 2024-10-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фотография товара', null=True, upload_to='products/', verbose_name='Фото'),
        ),
    ]
