# Generated by Django 5.1.1 on 2024-09-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_task_coins_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='coins_reward',
            field=models.PositiveIntegerField(help_text='Количество монет за выполнение задачи', verbose_name='Награда за выполнение (монеты)'),
        ),
    ]
