# Generated by Django 5.1.1 on 2024-10-01 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_alter_task_coins_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Команда, к которой относится задача', null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.team', verbose_name='Команда'),
        ),
    ]
