# Generated by Django 5.1.1 on 2024-10-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_task_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(help_text='Описание достижения', verbose_name='Описание'),
        ),
    ]
