# Generated by Django 5.1.1 on 2024-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_alter_achievement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='photo',
            field=models.ImageField(help_text='Фотография достижения', upload_to='achievements/', verbose_name='Фото'),
        ),
    ]
